### PR TITLE
add isCustomElement flag

### PR DESCRIPTION
**Pull request by thepassle**

### CODE REVIEW

**Comment by thepassle** [comment]
@justinfagnani Was a little bit unsure whether this should be on `CustomElement`, or as a required property on `ClassLike`, what do you think?

**Comment by justinfagnani** [comment]
@thepassle I think it should probably be non-optional on `CustomElement` and set to `true`. That should let it function as a type discriminator:

```
interface CustomElement extends ClassLike {
  customElement: true;
}
```

As far as naming, we haven't use the `isX` format yet - we have `static` and `optional`, not `isStatic` or `isOptional` - so I'd go with just `customElement`.

**Comment by thepassle** [comment]
@justinfagnani PTAL

**Comment by thepassle** [comment]
@justinfagnani friendly ping in case you missed this 🙂  This is the last thing we said we'd get in before V1 so it'd be nice to get this merged

**Comment by thepassle** [comment]
I'd kind of hate to delay things even further, but thinking more about this, maybe we should use the already existing `kind` field for this instead?

So instead of `"kind": "class"`, it would be `"kind": "custom-element"`. Considering we already have `"kind": "mixin"` this might make more sense than adding a dedicated boolean field (e.g. `customElement`) for it.

Example:
```diff
        {
+        "kind": "custom-element",
          "description": "",
          "name": "MyEl",
          "members": [],
          "attributes": [],
          "superclass": {
            "name": "HTMLElement"
          },
          "tagName": "my-el"
        }
```

**Comment by justinfagnani** [comment]
@thepassle with custom element declarations being a subclass of of class declarations, I think it'd be nice if code could list all the classes by filtering for `kind === 'class'`. Fundamentally a custom element definition is still a class, with additional fields.

**Review by justinfagnani — APPROVED** [review]

**Pull request merged**
